
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 19 15:23:06 BRT 2018
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int BECOMES = 4;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int SEMICOLON = 7;
  public static final int IDENTIFIER = 8;
  public static final int RETURN = 2;
  public static final int LPAREN = 5;
}

